import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Build tooling, not app source — plain Node/CJS scripts.
    "scripts/**",
    // Auto-generated by `npm run schema:update` — see .graphqlconfig.yml.
    "src/API.ts",
    "src/graphql/**",
  ]),
]);

export default eslintConfig;
