// Hand-authored, deliberately separate from the other files in this folder.
//
// Everything else in src/graphql/ is generated by `pnpm run schema:update`,
// which pulls the schema from the LIVE deployed AppSync API — so it can't
// include a field (Course.instructor) that only exists in the backend
// repo's source until that's actually deployed. Keeping these queries here
// means the public-browsing pages that need `instructor` are the only thing
// blocked on that deploy; every existing generated query (used by the
// already-working dashboard/builder pages) is untouched and keeps working
// regardless of deploy timing.
//
// Once the backend ships and `pnpm run schema:update` is re-run, this file
// can be deleted in favor of the regenerated `course`/`publicCourses`
// queries picking up `instructor` themselves — nothing here is meant to be
// permanent.

import { GraphQLClient } from '@/lib/graphql-client';
import type { CourseStatus } from '@/API';

export interface PublicCourseInstructor {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  avatarUrl?: string | null;
}

export interface PublicCourseOrganization {
  name: string;
}

export interface PublicCourse {
  id: string;
  title: string;
  description?: string | null;
  category?: string | null;
  thumbnailUrl?: string | null;
  priceTzs: number;
  status: CourseStatus;
  organization?: PublicCourseOrganization | null;
  instructor?: PublicCourseInstructor | null;
}

const COURSE_FIELDS = `
  id
  title
  description
  category
  thumbnailUrl
  priceTzs
  status
  organization { name }
  instructor { id firstName lastName avatarUrl }
`;

const publicCoursesQuery = /* GraphQL */ `
  query PublicCoursesWithInstructor {
    publicCourses {
      ${COURSE_FIELDS}
    }
  }
`;

const publicCourseDetailQuery = /* GraphQL */ `
  query CourseWithInstructor($id: ID!) {
    course(id: $id) {
      ${COURSE_FIELDS}
    }
  }
`;

export async function fetchPublicCourses(): Promise<PublicCourse[]> {
  const { publicCourses } = await GraphQLClient.execute<{ publicCourses: PublicCourse[] }>(publicCoursesQuery);
  return publicCourses;
}

export async function fetchPublicCourseDetail(id: string): Promise<PublicCourse | null> {
  const { course } = await GraphQLClient.execute<{ course: PublicCourse | null }>(publicCourseDetailQuery, { id });
  return course;
}

export function instructorDisplayName(course: PublicCourse): string | null {
  if (course.organization?.name) return course.organization.name;
  const instructor = course.instructor;
  if (!instructor) return null;
  const name = [instructor.firstName, instructor.lastName].filter(Boolean).join(' ').trim();
  return name || null;
}
